FROM node:8-alpine as builder


ADD ./back /app
WORKDIR /app
# RUN mkdir -p /dist

RUN npm -g config set user root
RUN npm install 
RUN npm install -g nodemon
RUN npm install -g mocha
RUN npm install typescript
RUN npm install ts-node